version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: Apex2
    volumes:
      - djambi-mysql-data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5100:5100"
    environment:
      - DJAMBI_Api__apiAddress=http://*:5100
      - DJAMBI_Api__cookieDomain=localhost
      - DJAMBI_Api__webAddress=http://localhost:8080
      - DJAMBI_Log__directory=
      - "DJAMBI_Sql__connectionString=Server=db;Port=3306;Database=Apex2;Uid=root;Pwd=devpassword;"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"

volumes:
  djambi-mysql-data:
