name: Check for API contract changes

on:
  push:
    branches:
      - master
      - develop
      - release/**
    paths:
      - api/api.web/**/*
      - api/api.enums/**/*
      - .github/workflows/check-for-api-contract-changes.yml
      - rest-client-generator/**/*

  pull_request:
    branches:
      - master
      - develop
      - release/**
    paths:
      - api/api.web/**/*
      - api/api.enums/**/*
      - .github/workflows/check-for-api-contract-changes.yml
      - rest-client-generator/**/*

jobs:
  build:

    runs-on: windows-latest # for powershell

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core # to build API
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dotnet tools
      run: dotnet tool restore
      working-directory: ./api

    - name: Restore API packages
      run: dotnet restore
      working-directory: ./api/api.host

    - name: Build API
      run: dotnet build -c release --no-restore
      working-directory: ./api/api.host

    - name: Setup Java # for OpenAPI generator
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Generate API client
      run: .\generate-api-client -sourcePath ../api/api.host/bin/release/net8.0/openapi.json -outDir ../web2/src/api-client
      working-directory: ./rest-client-generator

    - name: Check for uncommitted client changes
      run: .\check-if-client-changed
      working-directory: ./rest-client-generator