name: SQL Migration

on:
  push:
    branches: [ master ]
    paths:
      - api/api.db.model/**/*
      - .github/workflows/sql-migration.yml

env:
  DJAMBI_Sql__ConnectionString: ${{ secrets.SQL_CONNECTION_STRING }}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install EF Core tools
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore

    - name: Migrate
      run: dotnet-ef database update
      working-directory: ./api/api.db.model
